import { useEffect, useRef, useState, type ReactNode } from 'react';
import { AlertCircle, Check, LoaderCircle, Play, X } from 'lucide-react';
import { api, date, put, seconds } from './api';

export function Panel({ title, subtitle, actions, children }: { title: string; subtitle?: string; actions?: ReactNode; children: ReactNode }) {
  return <section className="panel"><div className="panel-head"><div><h3>{title}</h3>{subtitle && <p>{subtitle}</p>}</div>{actions}</div><div className="panel-body">{children}</div></section>;
}
export function Empty({ children = '暂无数据，请先完成上方操作。' }: { children?: ReactNode }) { return <div className="empty">{children}</div>; }
export function Badge({ status }: { status: string }) { const good = ['可用', 'completed', 'LOCKED'].includes(status); const bad = ['测试失败', 'failed', '未安装'].includes(status); const labels: Record<string, string> = { completed: '已完成', failed: '失败', queued: '排队中', running: '运行中', cancelled: '已取消' }; return <span className={`badge ${good ? 'good' : bad ? 'bad' : ''}`}>{labels[status] || status}</span>; }
export function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
export function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  useEffect(() => { const listener = (e: KeyboardEvent) => { if (e.key === 'Escape') close(); }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); }, [close]);
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h3>{title}</h3><button className="icon-button" aria-label="关闭" onClick={close}><X size={18} /></button></div>{children}</div></div>;
}
export function BusyButton({ busy, children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { busy?: boolean }) { return <button {...props} disabled={busy || props.disabled}>{busy && <LoaderCircle className="spin" size={15} />}{children}</button>; }
export function AudioPlayer({ fileId, segment, label = '试听' }: { fileId: string; segment?: any; label?: string }) {
  const ref = useRef<HTMLAudioElement>(null); const [open, setOpen] = useState(false);
  async function play() { setOpen(true); const audio = ref.current!; audio.currentTime = (segment?.start_ms || 0) / 1000; try { await audio.play(); } catch { /* User can use native audio controls after metadata loads. */ } }
  return <div className="audio-player"><button className="small" onClick={play}><Play size={12} />{label}</button><audio ref={ref} style={{ display: open ? 'block' : 'none' }} controls preload="none" src={`/api/files/${fileId}/audio`} onTimeUpdate={() => { if (segment && ref.current!.currentTime >= segment.end_ms / 1000) ref.current!.pause(); }} />{segment && <small>{seconds(segment.start_ms)} — {seconds(segment.end_ms)}</small>}</div>;
}
export function FilePicker({ files, selected, onChange, multiple = false, upload, busy }: { files: any[]; selected: string[]; onChange: (v: string[]) => void; multiple?: boolean; upload: (f: FileList) => void; busy: boolean }) {
  return <div><label className="upload"><span>＋ 上传新录音 <small>WAV / MP3 / M4A / FLAC / OGG · 最大500MB</small></span><input aria-label="上传录音" type="file" accept="audio/*" multiple disabled={busy} onChange={e => { if (e.target.files?.length) upload(e.target.files); e.target.value = ''; }} /></label>{files.length ? <div className="table-wrap"><table><thead><tr><th>选择</th><th>录音文件</th><th>时长 / 格式</th><th>试听</th></tr></thead><tbody>{files.map(f => <tr key={f.id} className={selected.includes(f.id) ? 'selected' : ''}><td><input aria-label={`选择 ${f.name}`} type={multiple ? 'checkbox' : 'radio'} checked={selected.includes(f.id)} onChange={() => onChange(multiple ? selected.includes(f.id) ? selected.filter(id => id !== f.id) : [...selected, f.id] : [f.id])} /></td><td><b>{f.name}</b><small>{date(f.created_at)}</small></td><td>{seconds(f.duration_ms)}<small>{f.sample_rate} Hz · {f.channels} 声道</small></td><td><AudioPlayer fileId={f.id} /></td></tr>)}</tbody></table></div> : <Empty>还没有录音。上传后可在所有实验中反复使用。</Empty>}</div>;
}
export function Review({ run, itemId, refresh }: { run: any; itemId: string; refresh: () => void }) {
  const old = run.reviews?.find((x: any) => x.item_id === itemId); const [verdict, setVerdict] = useState(old?.verdict || '待核验'); const [note, setNote] = useState(old?.note || ''); const [message, setMessage] = useState('');
  const choices = run.kind === 'E1' ? ['待核验', '正确', '同一人被拆成多个Speaker', '不同人被错误合并', '其它问题'] : ['待核验', '正确', '误识别', '漏识别', '其它问题'];
  return <div className="review"><select aria-label="人工核验结论" value={verdict} onChange={e => setVerdict(e.target.value)}>{choices.map(v => <option key={v}>{v}</option>)}</select><input aria-label="核验备注" placeholder="核验备注" value={note} onChange={e => setNote(e.target.value)} /><button className="small" onClick={async () => { try { await put(`/a01/runs/${run.id}/review`, { item_id: itemId, verdict, note }); setMessage('已保存'); refresh(); } catch (e: any) { setMessage(e.message); } }}><Check size={13} />保存</button>{message && <small role="status">{message}</small>}</div>;
}
export function Notice({ children, error = false }: { children: ReactNode; error?: boolean }) { return <div className={`notice ${error ? 'error' : ''}`}><AlertCircle size={16} /><div>{children}</div></div>; }
export function RunList({ runs, onOpen, selected, onSelect }: { runs: any[]; onOpen: (r: any) => void; selected?: string[]; onSelect?: (ids: string[]) => void }) {
  return runs.length ? <div className="table-wrap"><table><thead><tr>{onSelect && <th>选择</th>}<th>实验 / 时间</th><th>输入</th><th>状态</th><th>耗时</th><th>操作</th></tr></thead><tbody>{runs.map(r => <tr key={r.id}>{onSelect && <td><input type="checkbox" aria-label={`选择实验 ${r.id}`} checked={selected?.includes(r.id) || false} disabled={r.status !== 'completed'} onChange={() => onSelect(selected?.includes(r.id) ? selected.filter(x => x !== r.id) : [...(selected || []), r.id])} /></td>}<td><b>A01-{r.kind}</b><small>{date(r.created_at)}</small><code>{r.id.slice(0, 10)}</code></td><td>{r.inputs?.map((f: any) => f.name).join('、') || '麦克风实时流'}<small>{r.config.model_id || r.mode}</small></td><td><Badge status={r.status} /></td><td>{seconds(r.elapsed_ms)}</td><td><button className="small" onClick={() => onOpen(r)}>打开详情</button></td></tr>)}</tbody></table></div> : <Empty>暂无实验记录，每次运行会自动保存独立记录。</Empty>;
}
export function LiveView({ result }: { result: any }) {
  const timeline = result?.timeline || []; const last = timeline.at(-1); const metrics = result?.metrics;
  const end = Math.max(result?.duration_ms || 0, timeline.at(-1)?.decision_ms || 0, 1);
  return <><div className="kpis"><div><small>当前相似度</small><b>{last?.similarity == null ? '—' : last.similarity.toFixed(3)}</b></div><div><small>当前状态</small><b className="state">{last?.state || '等待输入'}</b></div><div><small>已处理音频</small><b>{seconds(result?.duration_ms)}</b></div><div><small>最新推理耗时</small><b>{last ? `${last.inference_ms.toFixed(0)} ms` : '—'}</b></div></div><div className="timeline" aria-label="Speaker Timeline">{timeline.map((r: any, i: number) => <span key={i} title={`${seconds(r.decision_ms)} ${r.state} 相似度 ${r.similarity ?? '无语音'}`} className={r.state.toLowerCase()} style={{ left: `${r.decision_ms / end * 100}%`, width: `${Math.max(0, ((timeline[i + 1]?.decision_ms || end) - r.decision_ms) / end * 100)}%` }} />)}</div><div className="legend"><i className="locked" />LOCKED <i className="candidate" />CANDIDATE <i className="unlocked" />UNLOCKED <i className="non_target" />NON_TARGET</div>{metrics && <><div className="kpis metric-grid">{[['首次锁定时延', metrics.first_lock_latency_ms], ['解锁平均时延', metrics.unlock_latency_ms], ['重新锁定平均时延', metrics.relock_latency_ms]].map(([label, value]) => <div key={label}><small>{label}</small><b>{seconds(value)}</b></div>)}<div><small>误锁次数</small><b>{metrics.false_locks ?? '—'}</b></div><div><small>目标覆盖率</small><b>{metrics.target_coverage == null ? '—' : `${(metrics.target_coverage * 100).toFixed(1)}%`}</b></div></div><Notice>{metrics.metric_note}</Notice></>}<div className="event-list">{timeline.filter((r: any) => r.event).map((r: any, i: number) => <span key={i}>{seconds(r.decision_ms)} <b>{r.event}</b></span>)}</div></>;
}
export function GroundTruthEditor({ run, refresh }: { run: any; refresh: () => void }) {
  const [text, setText] = useState((run.result?.ground_truth || []).map((s: any) => `${s.start_ms / 1000}, ${s.end_ms / 1000}`).join('\n')); const [message, setMessage] = useState('');
  return <div className="ground-truth"><Field label="目标人物 Ground Truth（秒，每行：开始,结束；留空表示整段没有目标）"><textarea placeholder="0.5, 6.2\n12, 18.5" value={text} onChange={e => setText(e.target.value)} /></Field><button onClick={async () => { try { const intervals = parseIntervals(text); await put(`/a01/runs/${run.id}/ground-truth`, { intervals }); setMessage('标注与正式指标已保存'); refresh(); } catch (e: any) { setMessage(e.message); } }}>保存标注并计算指标</button><small role="status">{message}</small></div>;
}
export function parseIntervals(text: string) { return text.trim() ? text.trim().split('\n').map(line => { const pair = line.split(/[,，]/).map(Number); if (pair.length !== 2 || pair.some(n => !Number.isFinite(n))) throw new Error('每行须为两个数字：开始秒数,结束秒数'); return { start_ms: pair[0] * 1000, end_ms: pair[1] * 1000 }; }) : []; }
export function RunDetail({ run, refresh }: { run: any; refresh: () => void }) {
  return <div className="stack"><div className="toolbar"><Badge status={run.status} /><code>{run.id}</code><span>{run.progress}</span>{['queued', 'running'].includes(run.status) && <button onClick={async () => { await api(`/a01/runs/${run.id}/cancel`, { method: 'POST' }); refresh(); }}>取消实验</button>}</div>{run.error && <Notice error>{run.error}</Notice>}{run.kind === 'E1' && run.result && <>{run.result.speakers.length === 0 && <Empty>{run.result.note}</Empty>}{run.result.speakers.map((speaker: any) => <div className="speaker-card" key={speaker.speaker_id}><h4>{speaker.speaker_id} <small>{seconds(speaker.total_duration_ms)} · {speaker.segments.length} 段</small></h4><div className="segment-list">{speaker.segments.map((segment: any) => <AudioPlayer key={segment.id} fileId={run.config.file_id} segment={segment} label={segment.overlap ? '重叠片段' : '试听片段'} />)}</div><Review run={run} itemId={speaker.speaker_id} refresh={refresh} /></div>)}</>}{run.kind === 'E2' && run.result?.files?.map((f: any) => <div className="speaker-card" key={f.file_id}><h4>{f.name}</h4><div className="toolbar"><Badge status={f.detected ? '识别到目标' : '未识别到目标'} /><span>最高相似度 {f.max_similarity == null ? '—' : f.max_similarity.toFixed(3)}</span></div><details><summary>全部 {f.segments.length} 个片段（含非目标，便于发现漏识别）</summary><div className="segment-list">{f.segments.map((seg: any) => <div key={seg.id}><b>{seg.target ? '目标' : '非目标'} · {seg.similarity.toFixed(3)}</b><AudioPlayer fileId={f.file_id} segment={seg} /></div>)}</div></details><Review run={run} itemId={f.file_id} refresh={refresh} /></div>)}{run.kind === 'E3' && <><LiveView result={run.result} />{run.inputs?.[0] && <AudioPlayer fileId={run.inputs[0].id} label="试听完整实验录音" />}{run.status === 'completed' && <><GroundTruthEditor key={run.id} run={run} refresh={refresh} /><Review run={run} itemId="run" refresh={refresh} /></>}</>}<details><summary>查看完整配置、原始输出和版本证据</summary><pre>{JSON.stringify(run, null, 2)}</pre></details></div>;
}
