import React, { useCallback, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowUpRight, Database, FlaskConical, Home, LogOut, Settings as SettingsIcon, ShieldCheck, X } from 'lucide-react';
import { api, date, post, seconds } from './api';
import { AudioPlayer, Badge, BusyButton, Empty, Modal, Notice, Panel, RunDetail, RunList } from './components';
import Settings from './Settings';
import A01 from './A01';
import './style.css';

const navA = [['A01', '目标人物声纹建立与实时识别'], ['A02', '流式语音实时识别'], ['A03', '复杂声音场景多目标人物混合识别'], ['A05', '实时图像 + 音频多模态实验']];
const navB = [['B01', '控制环路实验'], ['B02', '预测式认知与持续修正实验'], ['B03', '实时本体增量状态实验'], ['B04', '跨会议记忆与认知演化实验']];
const purposes: Record<string, string> = { A02: '验证持续音频到 Partial / Final 文本的真实流式识别，比较准确率、首字延迟和修正稳定性。', A03: '验证多人、打断和重叠讲话下，同时区分多个目标人物的能力。', A05: '验证实时图像与语音的对齐和联合理解，处理现场视觉指代。', B01: '验证不同时间尺度的事件控制、快速判断和认知决策环路的协同。', B02: '验证说话人尚未说完时的意图预测，以及持续修正、推翻和取消判断。', B03: '验证实时本体的增量状态更新，以及暂定、确认、取代和失效过程。', B04: '验证跨会议积累有证据、可修正的长期专业认知。' };

function App() {
  const [user, setUser] = useState<any>(undefined); const [page, setPage] = useState('home'); const [files, setFiles] = useState<any[]>([]); const [models, setModels] = useState<any[]>([]); const [runs, setRuns] = useState<any[]>([]); const [profiles, setProfiles] = useState<any[]>([]); const [reports, setReports] = useState<any[]>([]);
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<{ text: string; error: boolean } | null>(null); const [login, setLogin] = useState({ username: 'admin', password: '' }); const [warehouseTab, setWarehouseTab] = useState('files'); const [detailId, setDetailId] = useState(''); const [deleteTarget, setDeleteTarget] = useState<any>(null);
  const refresh = useCallback(async () => { const [f, m, r, p, a] = await Promise.all([api('/files'), api('/models/local'), api('/a01/runs'), api('/a01/target-profiles'), api('/reports')]); setFiles(f); setModels(m); setRuns(r); setProfiles(p); setReports(a); }, []);
  const act = useCallback(async (fn: () => Promise<any>) => { setBusy(true); setNotice(null); try { await fn(); } catch (e: any) { setNotice({ text: e.message || '操作失败，请检查后台状态', error: true }); } finally { setBusy(false); } }, []);
  useEffect(() => { void api('/me').then(setUser).catch(() => setUser(null)); const expire = () => setUser(null); window.addEventListener('session-expired', expire); return () => window.removeEventListener('session-expired', expire); }, []);
  useEffect(() => { if (!user) return; void refresh().catch(e => setNotice({ text: e.message, error: true })); let loading = false; const timer = setInterval(() => { if (loading) return; loading = true; void refresh().catch(e => setNotice({ text: e.message, error: true })).finally(() => { loading = false; }); }, 2000); return () => clearInterval(timer); }, [user, refresh]);
  async function upload(list: FileList) { const selected = Array.from(list); await act(async () => { for (const f of selected) { const data = new FormData(); data.append('file', f); await api('/files', { method: 'POST', body: data }); } await refresh(); setNotice({ text: `已上传 ${selected.length} 份录音，文件已保存到实验数据仓`, error: false }); }); }
  const logout = () => { setUser(null); setRuns([]); setFiles([]); setProfiles([]); setReports([]); setPage('home'); };
  const detail = runs.find(r => r.id === detailId);
  if (user === undefined) return <div className="loading-screen">正在连接妙悟实验室…</div>;
  if (!user) return <div className="login-page"><div className="login-intro"><span className="eyebrow">MIAOWU / REALTIME COGNITIVE INTELLIGENCE</span><h1>让认知能力，<br />在真实实验中生长。</h1><p>从一段声音开始，验证发现、识别与实时理解。</p><div className="login-visual"><Activity size={88} strokeWidth={1} /><div><b>01 / 声纹与实时识别</b><span>配置 · 运行 · 核验 · 洞察</span></div></div><small>妙悟 · 实时认知智能实验室 V0.1</small></div><form className="login-card" onSubmit={e => { e.preventDefault(); void act(async () => { const u = await post('/login', login); setUser(u); setLogin({ ...login, password: '' }); }); }}><div className="brand"><span className="logo">妙</span><div><h2>妙悟实验室</h2><small>实时认知智能实验工作台</small></div></div><h3>登录工作台</h3><p>继续你的认知智能实验。</p><label className="field"><span>用户名</span><input autoComplete="username" required value={login.username} onChange={e => setLogin({ ...login, username: e.target.value })} /></label><label className="field"><span>密码</span><input type="password" autoComplete="current-password" required value={login.password} onChange={e => setLogin({ ...login, password: e.target.value })} /></label>{notice && <Notice error>{notice.text}</Notice>}<BusyButton className="primary" busy={busy} type="submit">登录 <ArrowUpRight size={16} /></BusyButton><div className="login-hint">首次使用：admin / abcd@1234<br />登录后可在系统设置中修改密码。</div></form></div>;
  return <><header className="topbar"><div className="brand"><span className="logo">妙</span><div><h2>妙悟 · 实时认知智能实验室</h2><small>REALTIME COGNITIVE INTELLIGENCE LAB</small></div></div><div className="top-actions"><span className="local-status"><i />本地实验工作台</span><button onClick={() => setPage('warehouse')}><Database size={15} />实验数据仓</button><button onClick={() => setPage('settings')}><SettingsIcon size={15} />系统设置</button><button aria-label="退出登录" onClick={() => act(async () => { await post('/logout'); logout(); })}><LogOut size={15} />{user.username}</button></div></header><div className="shell"><aside className="sidebar"><button className={`home-link ${page === 'home' ? 'active' : ''}`} onClick={() => setPage('home')}><Home size={17} />首页<span>实验总览</span></button><div className="nav-label">基础能力实验 <span>FOUNDATION</span></div><nav>{navA.map(([id, text]) => <button className={`nav-item ${page === id ? 'active' : ''}`} key={id} onClick={() => setPage(id)}><code>{id}</code><span>{text}</span>{id === 'A01' && <i />}</button>)}</nav><div className="nav-label">认知能力实验 <span>COGNITION</span></div><nav>{navB.map(([id, text]) => <button className={`nav-item ${page === id ? 'active' : ''}`} key={id} onClick={() => setPage(id)}><code>{id}</code><span>{text}</span></button>)}</nav><div className="sidebar-footer"><FlaskConical size={18} /><b>Architecture Spike</b><small>设计一个 · 验证一个 · 真实实验</small><span>V0.1 / LOCAL WORKSPACE</span></div></aside><main>{busy && <div className="working-bar" role="status">正在处理，请稍候…</div>}{notice && <div className={`toast ${notice.error ? 'error' : ''}`} role="alert">{notice.text}<button aria-label="关闭通知" onClick={() => setNotice(null)}><X size={16} /></button></div>}
    {page === 'home' && <div className="stack"><div className="page-title"><div><span className="eyebrow">EXPERIMENT OVERVIEW</span><h1>每一个结论，都从真实实验开始。</h1><p>欢迎回来，{user.username}。在这里构建、验证和比较实时认知能力。</p></div><span className="version-tag">V0.1</span></div><div className="home-hero"><div><span className="eyebrow">当前重点 / A01</span><h2>目标人物声纹建立<br />与实时识别</h2><p>把会议里的人分清楚，认出目标人物，<br />再验证实时运行中能否快速、稳定地锁定。</p><button className="primary" onClick={() => setPage('A01')}>进入 A01 实验 <ArrowRightIcon /></button></div><div className="hero-flow">{['说话人发现', '目标人物识别', '实时锁定', '综合结论'].map((name, i) => <div key={name}><code>0{i + 1}</code><b>{name}</b><span>{['发现谁在说话', '确认这个人是谁', '观察真实锁定状态', '让证据形成结论'][i]}</span></div>)}</div></div><div className="stats-grid">{[[files.length, '实验录音', '所有录音永久保存，可重复使用'], [runs.length, '实验记录', '每轮配置与真实输出独立保存'], [reports.filter(r => r.type === 'report').length, '综合报告', '证据、核验和结论一并留存'], [models.filter(m => m.enabled && m.status === '可用').length, '可用本地模型', `${models.length} 个已注册模型`]].map(([value, label, sub]) => <div className="stat" key={label}><span>{label}</span><b>{value}</b><small>{sub}</small></div>)}</div><div className="two-col"><Panel title="最近的实验" actions={<button className="small" onClick={() => { setWarehouseTab('runs'); setPage('warehouse'); }}>查看全部 ↗</button>}><RunList runs={runs.slice(0, 4)} onOpen={(r: any) => setDetailId(r.id)} /></Panel><Panel title="实验准备"><div className="readiness"><ShieldCheck size={25} /><div><b>真实输入，真实推理，完整证据</b><p>先检查模型，再上传录音开始第一轮实验。未安装的模型会明确标记。</p></div></div>{models.map(m => <div className="model-summary" key={m.id}><span>{m.name}</span><Badge status={m.enabled ? m.status : '已停用'} /></div>)}<button className="mt" onClick={() => setPage('settings')}>管理模型与分析助手</button></Panel></div></div>}
    {page === 'A01' && <A01 {...{ files, models, runs, profiles, reports, refresh, act, busy, upload }} openRun={(r: any) => setDetailId(r.id)} />}
    {page === 'settings' && <Settings {...{ models, refresh, act, busy, user, logout }} />}
    {page === 'warehouse' && <div className="stack"><div className="page-title"><div><span className="eyebrow">EXPERIMENT DATA WAREHOUSE</span><h1>实验数据仓</h1><p>录音、每一轮实验和最终报告，都保存在这里。</p></div></div><div className="tabs">{[['files', '实验文件'], ['runs', '实验记录'], ['reports', '实验报告']].map(([id, label]) => <button key={id} className={id === warehouseTab ? 'active' : ''} onClick={() => setWarehouseTab(id)}>{label}</button>)}</div>{warehouseTab === 'files' && <Panel title={`实验文件 · ${files.length}`} actions={<label className="button primary file-button">＋ 上传文件<input aria-label="数据仓上传文件" type="file" accept="audio/*" multiple onChange={e => { if (e.target.files?.length) void upload(e.target.files); e.target.value = ''; }} /></label>}>{files.length ? <div className="table-wrap"><table><thead><tr><th>录音文件</th><th>时长 / 格式</th><th>文件证据</th><th>上传时间</th><th>操作</th></tr></thead><tbody>{files.map(f => <tr key={f.id}><td><b>{f.name}</b><small>{(f.bytes / 1024 / 1024).toFixed(2)} MB</small></td><td>{seconds(f.duration_ms)}<small>{f.sample_rate}Hz · {f.channels}声道</small></td><td><details><summary>SHA256</summary><code className="hash">{f.sha256}</code></details></td><td>{date(f.created_at)}</td><td><AudioPlayer fileId={f.id} /><button className="small danger" onClick={() => setDeleteTarget(f)}>删除</button></td></tr>)}</tbody></table></div> : <Empty>上传第一份录音，开启实验。</Empty>}</Panel>}{warehouseTab === 'runs' && <Panel title="全部实验记录"><RunList runs={runs} onOpen={(r: any) => setDetailId(r.id)} /></Panel>}{warehouseTab === 'reports' && <Panel title="已保存报告">{reports.filter(r => r.type === 'report').length ? reports.filter(r => r.type === 'report').map(r => <div className="report-row" key={r.id}><div><b>{r.name}</b><small>{date(r.created_at)} · {r.run_ids.length} 轮实验 · {r.analysis_id ? '含智能分析' : '实验证据汇总'}</small></div><div className="actions">{['md', 'csv', 'json'].map(ext => <a className="button small" key={ext} href={`/api/reports/${r.id}/${ext}`} download>{ext.toUpperCase()} ↓</a>)}</div></div>) : <Empty>在 A01 第04步生成报告后，可在此重新下载。</Empty>}</Panel>}</div>}
    {purposes[page] && <div className="stack"><div className="page-title"><div><span className="eyebrow">EXPERIMENT / {page}</span><h1>{[...navA, ...navB].find(([id]) => id === page)?.[1]}</h1></div></div><Panel title="实验目的"><p>{purposes[page]}</p><Empty><FlaskConical size={36} /><h3>等待下一阶段设计与开发</h3><p>V0.1 按开发方案先完成 A01，此实验保留导航占位。</p><button onClick={() => setPage('A01')}>进入当前 A01 实验</button></Empty></Panel></div>}
  </main></div>{detail && <Modal title={`A01-${detail.kind} 实验详情`} close={() => setDetailId('')}><RunDetail run={detail} refresh={refresh} /></Modal>}{deleteTarget && <Modal title="删除实验录音" close={() => setDeleteTarget(null)}><p>将删除“{deleteTarget.name}”及其原始文件。已经被实验引用的录音会保留。</p><div className="modal-actions"><button onClick={() => setDeleteTarget(null)}>取消</button><BusyButton className="danger" busy={busy} onClick={() => act(async () => { await api(`/files/${deleteTarget.id}`, { method: 'DELETE' }); setDeleteTarget(null); await refresh(); })}>删除文件</BusyButton></div></Modal>}</>;
}
function ArrowRightIcon() { return <ArrowUpRight size={16} />; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
