import { useEffect, useState } from 'react';
import { api, post, put } from './api';
import { Badge, BusyButton, Empty, Field, Modal, Notice, Panel } from './components';

export default function Settings({ models, refresh, act, busy, user, logout }: any) {
  const [tab, setTab] = useState('models'); const [services, setServices] = useState<any[]>([]); const [users, setUsers] = useState<any[]>([]); const [agent, setAgent] = useState<any>(null); const [editor, setEditor] = useState<any>(null); const [testResult, setTestResult] = useState<any>(null); const [password, setPassword] = useState({ current_password: '', new_password: '' });
  async function reload() { const a = await api('/agent'); setAgent(a); if (user.role === '管理员') { const [s, u] = await Promise.all([api('/model-services'), api('/users')]); setServices(s); setUsers(u); } }
  useEffect(() => { void act(reload); }, []);
  const update = (key: string, value: any) => setEditor({ ...editor, value: { ...editor.value, [key]: value } });
  const defaults: any = {
    local: { name: '', capability: '目标说话人识别', load_mode: 'Python 模块', adapter: 'wespeaker', path: '', device: 'cpu', enabled: true, note: '' },
    service: { name: '', provider: 'OpenAI Compatible', base_url: '', api_key: null, timeout: 60, models: [], default_model: '', enabled: true, note: '' },
    user: { username: '', password: '', role: '实验员', enabled: true }
  };
  async function saveEditor(test = false) {
    let data = { ...editor.value }; const type = editor.type;
    if (type === 'service') { if (!data.default_model) data.default_model = data.models[0] || ''; }
    const base = type === 'local' ? '/models/local' : type === 'service' ? '/model-services' : '/users';
    const saved = editor.id ? await put(`${base}/${editor.id}`, data) : await post(base, data);
    if (test && type !== 'user') setTestResult(await post(`${base}/${saved.id}/test`));
    setEditor(null); await refresh(); await reload();
  }
  return <div className="stack"><div className="page-title"><div><span className="eyebrow">WORKSPACE SETTINGS</span><h1>系统设置</h1><p>管理本地推理能力、模型服务与实验分析助手。</p></div></div><div className="tabs">{[['models', '模型注册'], ['agent', '辅助分析智能助手'], ['users', '用户与账号']].map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}</div>
    {tab === 'models' && <><Panel title="本地模型" subtitle="后台直接加载运行；测试会使用本地真实语音样本执行推理。" actions={user.role === '管理员' && <button className="primary" onClick={() => setEditor({ type: 'local', value: defaults.local })}>＋ 注册本地模型</button>}><div className="table-wrap"><table><thead><tr><th>模型名称 / 能力</th><th>路径 / 版本</th><th>运行设备</th><th>状态</th><th>操作</th></tr></thead><tbody>{models.map((m: any) => <tr key={m.id}><td><b>{m.name}</b><small>{m.capability} · {m.load_mode}</small></td><td className="path-cell"><code>{m.path}</code><small>{m.version || '尚未下载'}<br />{m.note}</small>{m.error && <small className="error-text">{m.error}</small>}</td><td>{m.device}</td><td><Badge status={m.enabled ? m.status : '已停用'} /></td><td>{user.role === '管理员' && <div className="actions"><button className="small" onClick={() => setEditor({ type: 'local', id: m.id, value: { ...m } })}>编辑</button><BusyButton className="small" busy={busy} onClick={() => act(async () => { setTestResult(await post(`/models/local/${m.id}/test`)); await refresh(); })}>测试</BusyButton><button className="small" disabled={busy} onClick={() => act(async () => { await put(`/models/local/${m.id}`, { ...m, enabled: !m.enabled }); await refresh(); })}>{m.enabled ? '停用' : '启用'}</button>{['campp', 'wespeaker', 'vad', 'paraformer', 'pyannote'].includes(m.id) && <button className="small" disabled={m.status === '下载中' || busy} onClick={() => act(async () => { await post(`/models/local/${m.id}/download`); await refresh(); })}>下载 / 重试</button>}</div>}</td></tr>)}</tbody></table></div><Notice>pyannote 须先接受官方模型协议并设置本机 HF_TOKEN，重启后端后点击下载。原型中的 WeSpeaker ECAPA 标识以实际安装的官方中文 ResNet34-LM 为准。</Notice></Panel>
    {user.role === '管理员' && <Panel title="模型服务" subtitle="HTTP/API 服务统一注册；列表不显示 API Key。" actions={<button className="primary" onClick={() => setEditor({ type: 'service', value: defaults.service })}>＋ 注册模型服务</button>}>{services.length ? <div className="table-wrap"><table><thead><tr><th>服务 / Provider</th><th>API 地址</th><th>可用模型</th><th>状态</th><th>操作</th></tr></thead><tbody>{services.map(s => <tr key={s.id}><td><b>{s.name}</b><small>{s.provider} · {s.has_api_key ? '密钥已配置' : '无密钥'}</small></td><td>{s.base_url}</td><td>{s.models.join('、')}<small>默认：{s.default_model}</small></td><td><Badge status={s.enabled ? s.status : '已停用'} />{s.error && <small className="error-text">{s.error}</small>}</td><td><div className="actions"><button className="small" onClick={() => setEditor({ type: 'service', id: s.id, value: { ...s, api_key: null } })}>编辑</button><BusyButton className="small" busy={busy} onClick={() => act(async () => { setTestResult(await post(`/model-services/${s.id}/test`)); await reload(); })}>测试</BusyButton><button className="small" onClick={() => act(async () => { await put(`/model-services/${s.id}`, { ...s, api_key: null, enabled: !s.enabled }); await reload(); })}>{s.enabled ? '停用' : '启用'}</button></div></td></tr>)}</tbody></table></div> : <Empty>尚未配置模型服务。注册真实服务后即可使用综合分析。</Empty>}</Panel>}</>}
    {tab === 'agent' && agent && <Panel title="辅助分析智能助手" subtitle="所选实验的文件名称、参数、结果和人工核验将发送至此服务。">{user.role !== '管理员' ? <Notice>当前助手：{agent.name} / {agent.model || '未配置'}。请由管理员修改配置。</Notice> : <div className="stack"><div className="form-grid"><Field label="智能体名称"><input value={agent.name} onChange={e => setAgent({ ...agent, name: e.target.value })} /></Field><Field label="模型服务"><select value={agent.service_id} onChange={e => { const service = services.find(s => s.id === e.target.value); setAgent({ ...agent, service_id: e.target.value, model: service?.default_model || '' }); }}><option value="">请选择服务</option>{services.filter(s => s.enabled).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="模型名称"><select value={agent.model} onChange={e => setAgent({ ...agent, model: e.target.value })}><option value="">请选择模型</option>{services.find(s => s.id === agent.service_id)?.models.map((m: string) => <option key={m}>{m}</option>)}</select></Field><Field label="Temperature"><input type="number" min="0" max="2" step="0.1" value={agent.temperature} onChange={e => setAgent({ ...agent, temperature: Number(e.target.value) })} /></Field><Field label="Max Tokens"><input type="number" min="100" max="32000" value={agent.max_tokens} onChange={e => setAgent({ ...agent, max_tokens: Number(e.target.value) })} /></Field></div><Field label="System Prompt"><textarea rows={6} value={agent.system_prompt} onChange={e => setAgent({ ...agent, system_prompt: e.target.value })} /></Field><div className="actions"><BusyButton busy={busy} className="primary" onClick={() => act(async () => { await put('/agent', agent); await reload(); })}>保存助手配置</BusyButton><BusyButton busy={busy} onClick={() => act(async () => { await put('/agent', agent); setTestResult(await post('/agent/test')); })}>保存并真实测试</BusyButton></div></div>}</Panel>}
    {tab === 'users' && <>{user.role === '管理员' && <Panel title="用户管理" actions={<button className="primary" onClick={() => setEditor({ type: 'user', value: defaults.user })}>＋ 新增用户</button>}><table><thead><tr><th>用户名</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>{users.map(u => <tr key={u.id}><td>{u.username}</td><td>{u.role}</td><td><Badge status={u.enabled ? '启用' : '停用'} /></td><td><button className="small" disabled={u.id === user.id} onClick={() => act(async () => { await put(`/users/${u.id}`, { role: u.role, enabled: !u.enabled }); await reload(); })}>{u.enabled ? '停用' : '启用'}</button></td></tr>)}</tbody></table></Panel>}<Panel title="修改当前账号密码" subtitle="修改后所有现有会话失效，请重新登录。"><form onSubmit={e => { e.preventDefault(); void act(async () => { await post('/password', password); logout(); }); }}><div className="form-grid"><Field label="当前密码"><input type="password" autoComplete="current-password" required value={password.current_password} onChange={e => setPassword({ ...password, current_password: e.target.value })} /></Field><Field label="新密码（至少8位）"><input type="password" autoComplete="new-password" required minLength={8} value={password.new_password} onChange={e => setPassword({ ...password, new_password: e.target.value })} /></Field></div><BusyButton busy={busy} className="primary mt" type="submit">修改密码</BusyButton></form></Panel></>}
    {editor && <Modal title={editor.type === 'local' ? '本地模型配置' : editor.type === 'service' ? '模型服务配置' : '新增用户'} close={() => setEditor(null)}><form onSubmit={e => { e.preventDefault(); void act(() => saveEditor()); }}><div className="stack">
      {editor.type === 'local' && <><Field label="模型名称"><input required value={editor.value.name} onChange={e => update('name', e.target.value)} /></Field><div className="form-grid"><Field label="能力类型"><select value={editor.value.capability} onChange={e => update('capability', e.target.value)}>{['流式语音识别', '说话人发现', '目标说话人识别', '语音活动检测'].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="加载方式"><select value={editor.value.load_mode} onChange={e => setEditor({ ...editor, value: { ...editor.value, load_mode: e.target.value, adapter: e.target.value === '命令行进程' ? 'command' : 'wespeaker' } })}><option>Python 模块</option><option>命令行进程</option></select></Field><Field label="推理适配器"><select value={editor.value.adapter} onChange={e => update('adapter', e.target.value)}>{(editor.value.load_mode === '命令行进程' ? ['command'] : ['campp', 'wespeaker', 'pyannote', 'vad', 'paraformer']).map(v => <option key={v}>{v}</option>)}</select></Field><Field label="运行设备"><select value={editor.value.device} onChange={e => update('device', e.target.value)}><option value="cpu">CPU</option><option value="cuda">CUDA</option><option value="auto">自动</option></select></Field></div><Field label="模型目录 / ONNX文件 / 可执行文件路径"><input required value={editor.value.path} onChange={e => update('path', e.target.value)} /></Field><Field label="备注"><textarea value={editor.value.note} onChange={e => update('note', e.target.value)} /></Field></>}
      {editor.type === 'service' && <><Field label="服务名称"><input required value={editor.value.name} onChange={e => update('name', e.target.value)} /></Field><Field label="Provider"><input value={editor.value.provider} onChange={e => update('provider', e.target.value)} /></Field><Field label="API Base URL（包含 /v1，如适用）"><input type="url" required placeholder="https://example.com/v1" value={editor.value.base_url} onChange={e => update('base_url', e.target.value)} /></Field><Field label="API Key（留空保留已有密钥）"><input type="password" autoComplete="new-password" value={editor.value.api_key || ''} onChange={e => update('api_key', e.target.value || null)} /></Field>{editor.id && <label className="check-label"><input type="checkbox" checked={editor.value.api_key === ''} onChange={e => update('api_key', e.target.checked ? '' : null)} />清除已有密钥</label>}<Field label="可用模型（英文逗号分隔）"><input required value={editor.value.models.join(',')} onChange={e => update('models', e.target.value.split(',').map(x => x.trim()))} /></Field><Field label="默认模型"><input placeholder="留空使用第一个模型" value={editor.value.default_model} onChange={e => update('default_model', e.target.value)} /></Field><Field label="请求超时（秒）"><input type="number" min="1" max="600" value={editor.value.timeout} onChange={e => update('timeout', Number(e.target.value))} /></Field><Field label="备注"><textarea value={editor.value.note} onChange={e => update('note', e.target.value)} /></Field></>}
      {editor.type === 'user' && <><Field label="用户名"><input required value={editor.value.username} onChange={e => update('username', e.target.value)} /></Field><Field label="初始密码"><input type="password" required minLength={8} value={editor.value.password} onChange={e => update('password', e.target.value)} /></Field><Field label="角色"><select value={editor.value.role} onChange={e => update('role', e.target.value)}><option>实验员</option><option>管理员</option></select></Field></>}
      <div className="modal-actions"><button type="button" onClick={() => setEditor(null)}>取消</button>{editor.type !== 'user' && <BusyButton busy={busy} type="button" onClick={() => act(() => saveEditor(true))}>保存并测试</BusyButton>}<BusyButton busy={busy} className="primary" type="submit">保存</BusyButton></div></div></form></Modal>}
    {testResult && <Modal title="真实测试结果" close={() => setTestResult(null)}>{testResult.status && <Badge status={testResult.status} />}<pre>{JSON.stringify(testResult, null, 2)}</pre></Modal>}
  </div>;
}
